import { it } from '../test-utils'

it('5 + 5', 10)
it('5 - 5', 0)
it('5 * 5', 25)
it('5 / 5', 1)
it('5 % 5', 0)
it('5 ** 5', 3125)
it('5 == 5', true)
it('5 === 5', true)
it('5 != 5', false)
it('5 !== 5', false)
it('5 < 5', false)
it('5 <= 5', true)
it('5 > 5', false)
it('5 >= 5', true)
it('1 in {}', false)
it('1 in ["a", "b"]', true)
it('"a" in { a: 1 }', true)
it('"b" in { a: 1 }', false)
it('({}) instanceof Object', true)
it('({}) instanceof Array', false)
